global using AutoMapper;
global using Bookify.web.Core.Conts;
global using Bookify.web.Core.Models;
global using Bookify.web.Core.ViewModels;
global using Bookify.web.Data;
global using Bookify.web.Filters;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
